<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="52143" started-at="2019-03-02T17:07:36Z" finished-at="2019-03-02T17:08:28Z">
    <groups>
    </groups>
    <test name="RegistrationTest" duration-ms="52143" started-at="2019-03-02T17:07:36Z" finished-at="2019-03-02T17:08:28Z">
      <class name="web.Tests.RegistrationTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:web.Tests.RegistrationTest@6f8c7ccd]" name="setUp" is-config="true" duration-ms="5167" started-at="2019-03-02T21:07:36Z" finished-at="2019-03-02T21:07:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="registerUser()[pri:1, instance:web.Tests.RegistrationTest@6f8c7ccd]" name="registerUser" duration-ms="46831" started-at="2019-03-02T21:07:41Z" finished-at="2019-03-02T21:08:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[SignUp Success expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: SignUp Success expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at web.Tests.RegistrationTest.registerUser(RegistrationTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerUser -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:web.Tests.RegistrationTest@6f8c7ccd]" name="tearDown" is-config="true" duration-ms="136" started-at="2019-03-02T21:08:28Z" finished-at="2019-03-02T21:08:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- web.Tests.RegistrationTest -->
    </test> <!-- RegistrationTest -->
  </suite> <!-- Suite -->
</testng-results>
